services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #    volumes:
    #      - mysql_data:/var/lib/mysql
    networks:
      - petory-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6381:6379"
    networks:
      - petory-network

  mongodb:
    image: mongo:latest
    container_name: mongodb_boot
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - petory-network

  prometheus:
    image: prom/prometheus
    container_name: prom
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - petory-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - petory-network

volumes:
  mysql_data:
  mongodb_data:

networks:
  petory-network:
